function rotarPalabrasClave() {
    const palabrasClave = [
"?q=online+mba+programs+for+international+students",
"?q=online+business+schools",
"?q=online+mba+programs",
"?q=mba+information",
"?q=accredited+online+mba+programs",
"?q=online+masters+in+business",
"?q=master+mba+online",
"?q=mba+programs+near+me",
"?q=distance+mba+course",
"?q=online+mba+finance+programs",
"?q=mba+healthcare+management+online",
"?q=online+mba",
"?q=masters+in+business+analytics+online",
"?q=mba+near+me",
"?q=mba+degree+online",
"?q=master+of+business+administration+online",
"?q=mba+on+line",
"?q=mba+marketing+online",
"?q=distance+learning+mba",
"?q=best+online+mba+programs",
"?q=top+online+mba+programs",
"?q=top+online+mba",
"?q=online+mba+courses",
"?q=online+mba+for+working+professionals",
"?q=masters+in+healthcare+management",
"?q=one+year+online+mba",
"?q=1+year+online+mba",
"?q=mba+finance+online",
"?q=mba+admissions+consulting",
"?q=mba+distance+education",
"?q=mba+colleges+near+me",
"?q=accelerated+mba+programs",
"?q=lsu+online+mba",
"?q=executive+mba+for+working+professionals",
"?q=masters+degree+in+business+management",
"?q=distance+mba",
"?q=mba+programs",
"?q=best+online+marketing+mba",
"?q=getting+an+mba",
"?q=affordable+online+mba+programs",
"?q=affordable+online+mba",
"?q=online+executive+mba",
"?q=mba+for+working+professionals",
"?q=bachelor+degree+business+administration",
"?q=best+online+mba",
"?q=ba+mba",
"?q=mba+classes+near+me",
"?q=master's+degree+in+business+administration",
"?q=mba+business+administration",
"?q=mba+master+of+business+administration",
"?q=master+of+business+admin",
"?q=part+time+mba+programs",
"?q=mba+without+degree",
"?q=mba+in+marketing+management",
"?q=mba+consulting",
"?q=asu+online+mba",
"?q=masters+in+business+management",
"?q=mba+in+healthcare+management",
"?q=mba+in+accounting+and+finance",
"?q=mba+in+sustainability+management",
"?q=mba+in+hr",
"?q=mba+in+human+resource+management",
"?q=mba+in+hr+management",
"?q=mba+human+resources",
"?q=marketing+week+mini+mba",
"?q=marketing+schools",
"?q=mba+in+supply+chain+management",
"?q=one+year+mba+programs",
"?q=1+year+mba+programs",
"?q=mba+supply+chain",
"?q=pursuing+mba",
"?q=mba+in+healthcare+administration",
"?q=mba+in+logistics+and+supply+chain+management",
"?q=master+of+hospital+administration",
"?q=master+in+healthcare+administration",
"?q=mba+marketing",
"?q=international+mba+programs",
"?q=msn+mba+dual+degree",
"?q=masters+in+business",
"?q=cheapest+mba+programs",
"?q=affordable+mba+programs",
"?q=mba+in+business+management",
"?q=business+masters+degrees",
"?q=best+online+mba+in+the+world",
"?q=fast+track+mba",
"?q=healthcare+mba",
"?q=accelerated+mba",
"?q=cheapest+online+mba",
"?q=most+affordable+online+mba",
"?q=mba+master+degree",
"?q=business+school",
"?q=b+schools",
"?q=mba+in+hospitality+management",
"?q=mba+accounting",
"?q=mark+ritson+mini+mba",
"?q=mini+mba+mark+ritson",
"?q=mba+in+business+analytics",
"?q=mba+in+hospital+management",
"?q=mba+in+hospital+administration",
"?q=mba+in+hospital+and+healthcare+management"]; // Reemplaza con tus palabras clave
    
    // Obtener un índice aleatorio
    const indiceAleatorio = Math.floor(Math.random() * palabrasClave.length);

    // Obtener todos los elementos con el ID "randKey" utilizando querySelectorAll
    const elementos = document.querySelectorAll("#randKey");
    
    elementos.forEach((elemento) => {
        // Agregar la palabra clave aleatoria a los enlaces encontrados
        elemento.href = palabrasClave[indiceAleatorio];
    });
}

// Obtener todos los elementos con el ID "randKey" utilizando querySelectorAll
const botones = document.querySelectorAll("#randKey");

botones.forEach((boton) => {
    // Agregar un evento de clic a los botones encontrados
    boton.addEventListener("click", rotarPalabrasClave);
});
